# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SongSearcher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SongSearcher
  pod "PromiseKit", "~> 6.8"
  pod 'Kingfisher'
  pod 'JGProgressHUD'

end
